### ISSUE TITLE
Some error in project

### ISSUE THREAD

**Issue by taufik1993** [amanjeetsingh150/kotlin-android-examples#4]
I have download project as it is. But one class not found in your project that the reason i am not able to run this project.

Question 1. This class not found:-
import com.developers.mvvmsample.di.components.DaggerActivityComponent

Question  2. I am getting error compile time

Folder D:\AndroidProjects\CompanyProjects\Msmadhan\Kotlin\v1_Test\app\build\generated\source\kaptKotlin\debug
Folder D:\AndroidProjects\CompanyProjects\Msmadhan\Kotlin\v1_Test\app\build\generated\source\kaptKotlin\release
3rd-party Gradle plug-ins may be the cause

I have already seen below url but solution not working:-
https://stackoverflow.com/questions/49518223/3rd-party-gradle-plug-ins-may-be-the-cause

If i am wrong then suggest me what should i do.

**Comment by amanjeetsingh150** [comment]
Hey @taufik1993 , This component is automatically generated by Dagger you should try clean and make project from Android Studio and try that if it gets generated properly.
Do tell me if it still not runs :+1:

**Comment by taufik1993** [comment]
Hey @amanjeetsingh150, thanks for rply, i have seen same error after clean project and  rebuild again. this is not solve my error
![untitled](https://user-images.githubusercontent.com/29916053/46245354-fa6d0a80-c409-11e8-804e-20c301055257.png)

**Comment by radityagumay** [comment]
@taufik1993 try to using command line if from IDE didn't works. 

./gradlew clean :app:assembleDebug

**Comment by taufik1993** [comment]
Awesome, @radityagumay thanks

**Comment by amanjeetsingh1mg** [comment]
Hey @radityagumay Thanks for the help. Hope that solution worked @taufik1993 .
Feel free to reopen the issue if it not works.

Thanks 👍
