### ISSUE TITLE
Examples Cannot be Downloaded

### ISSUE THREAD

**Issue by TheDeepThinker** [amanjeetsingh150/kotlin-android-examples#6]
Download links for the [examples](https://github.com/amanjeetsingh150/kotlin-android-examples#examples) do not work.

**Comment by TheDeepThinker** [comment]
Like, this link does not work: http://kinolien.github.io/gitzip/?download=https://github.com/amanjeetsingh150/kotlin-android-examples/tree/master/ActivityLifecycle

**Comment by amanjeetsingh150** [comment]
Hey @TheDeepThinker did you generated your token first and put it in the dashboard?

**Comment by TheDeepThinker** [comment]
Shouldn't we be able to download it without token?

**Comment by amanjeetsingh150** [comment]
Hey, @TheDeepThinker Sorry for the late reply. I checked this link and its working.
1. Just remember to open the link a dialog will appear asking you for token. Close it
2. Click Download on top right corner of your screen it will start to download.

Do tell if this does not works

**Comment by TheDeepThinker** [comment]
I tried several times as you mentioned (later downloaded the whole directory :smiling_imp: ).

**Comment by TheDeepThinker** [comment]
You may use downgit in your project like this- https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/amanjeetsingh150/kotlin-android-examples/tree/master/ActivityLifecycle

**Comment by amanjeetsingh150** [comment]
Closing the issue as it seems resolved now. Feel free to reopen 👍
